package api

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/emelvv/tvpoll/internal/model"
)

func uuid() (string, error) {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	s := hex.EncodeToString(b)
	return s[:8] + "-" + s[8:12] + "-" + s[12:16] + "-" + s[16:20] + "-" + s[20:], nil
}

func validID(s string) bool {
	if len(s) != 36 || strings.ToLower(s) != s {
		return false
	}
	for n, c := range s {
		if n == 8 || n == 13 || n == 18 || n == 23 {
			if c != '-' {
				return false
			}
		} else if !(c >= '0' && c <= '9' || c >= 'a' && c <= 'f') {
			return false
		}
	}
	return true
}

func validatePoll(p *model.Poll, now time.Time) error {
	if p.ID != "" {
		return errors.New("id is generated by the server")
	}
	p.Question = strings.TrimSpace(p.Question)
	if !utf8.ValidString(p.Question) || utf8.RuneCountInString(p.Question) < 1 || utf8.RuneCountInString(p.Question) > 500 {
		return errors.New("question must contain 1..500 characters")
	}
	if len(p.Options) < 2 || len(p.Options) > 32 {
		return errors.New("provide 2..32 options")
	}
	seen := map[string]bool{}
	for n, o := range p.Options {
		o = strings.TrimSpace(o)
		if !utf8.ValidString(o) || utf8.RuneCountInString(o) < 1 || utf8.RuneCountInString(o) > 200 {
			return errors.New("options must contain 1..200 characters")
		}
		key := strings.ToLower(o)
		if seen[key] {
			return errors.New("option labels must be distinct")
		}
		seen[key] = true
		p.Options[n] = o
	}
	if p.MinChoices == 0 {
		p.MinChoices = 1
	}
	switch p.Type {
	case "single":
		if p.MaxChoices == 0 {
			p.MaxChoices = 1
		}
		if p.MinChoices != 1 || p.MaxChoices != 1 {
			return errors.New("single polls require min_choices=max_choices=1")
		}
	case "multiple":
		if p.MaxChoices == 0 {
			p.MaxChoices = len(p.Options)
		}
	default:
		return errors.New("type must be single or multiple")
	}
	if p.MinChoices < 1 || p.MaxChoices < p.MinChoices || p.MaxChoices > len(p.Options) {
		return errors.New("invalid choice limits")
	}
	if p.OpensAt.IsZero() || p.ClosesAt.IsZero() || !p.ClosesAt.After(p.OpensAt) || p.ClosesAt.Sub(p.OpensAt) > 24*time.Hour {
		return errors.New("opens_at and closes_at must define a window up to 24 hours")
	}
	// A past window is allowed so an idempotent create can be replayed after close.
	p.OpensAt = p.OpensAt.UTC()
	p.ClosesAt = p.ClosesAt.UTC()
	return nil
}

func choiceMask(p model.Poll, choices []int) (int64, error) {
	if len(choices) < p.MinChoices || len(choices) > p.MaxChoices {
		return 0, fmt.Errorf("select %d..%d options", p.MinChoices, p.MaxChoices)
	}
	var mask int64
	for _, c := range choices {
		if c < 0 || c >= len(p.Options) {
			return 0, errors.New("unknown option")
		}
		bit := int64(1) << c
		if mask&bit != 0 {
			return 0, errors.New("duplicate option")
		}
		mask |= bit
	}
	return mask, nil
}
